### ISSUE TITLE
Adapt supported algorithms

### ISSUE THREAD

**Issue by lisaTeis** [secureCryptoConfig/secureCryptoConfigInterface#16]
Interface | COSE | Java
-- | -- | --
Symmetric |   |  
AES_GCM_256_96 | AES_GCM_256 | AES/GCM/NoPadding, 256 key
AES_GCM_128_96 | AES_GCM_128 | AES/GCM/NoPadding, 128 key
AES_GCM_192_96 | AES_GCM_192 | AES/GCM/NoPadding, 192 key
Asymmetric |   |  
RSA_SHA_512 | RSA_OAEP_SHA_512 | RSA/ECB/OAEPWithSHA-512AndMGF1Padding
RSA_SHA_256 | RSA_OAEP_SHA_256 | RSA/ECB/OAEPWithSHA-256AndMGF1Padding
RSA_ECB | RSA_ECB | RSA/ECB/PKCS1Padding
Digital signature |   |  
ECDSA_512 | ECDSA_512 | SHA512withECDSA
ECDSA_256 | ECDSA_256 | SHA256withECDSA
ECDSA_384 | ECDSA_384 | SHA2384withECDSA
Hash |   |  
SHA_512 | SHA_512 | SHA-512
SHA_256 | SHA_256 | SHA-256
SHA3_512 | SHA3_512 | SHA3-512
SHA3_256 | SHA3_256 | SHA3-256
Password Hash |   |  
PBKDF_SHA_512 | PBKDF_SHA_512 | PBKDF2WithHmacSHA512
PBKDF_SHA_256 | PBKDF_SHA_256 | PBKDF2WithHmacSHA256
SHA_512_64 (64 Salt) | SHA_512_64 | SHA-512

**Comment by kmindi** [comment]
@lisaTeis can you add all of these algorithms (see issue description)?

**Comment by lisaTeis** [comment]
@kmindi Wo finde ich die Algorithmen? Ich kann sie gerade nicht finden

**Comment by kmindi** [comment]
hmm es hat das nicht gespeichert, jetzt habe ich es nochmal aktualisiert, aber es sind einfach alle aus deiner excel datei :-D
