### ISSUE TITLE
PlainTextContainer has no validateSignature method?

### ISSUE THREAD

**Issue by kmindi** [secureCryptoConfig/secureCryptoConfigInterface#21]
There is a sign method, but no validateSignautre method. Shouldn't there be one?

E.g. `boolean validateSignature(SCCKey, SCCSignature)`

**Comment by lisaTeis** [comment]
Ich denke nicht, dass wir auf dem PlaintextContainer eine validateSignature methode brauchen. Die braucht man doch nur in der SCCSignature Klasse. Man kann ja nur die Signatur und nicht den Plaintext validieren (bzgl der digitalen Signatur) oder war deine Intention anders?

**Comment by kmindi** [comment]
Und wie prüfe ich dann ob die signatur zum text passt? Also der Text korrekt signiert ist?
Beispiel: Die Bank bekommt eine E-Mail mit dem Inhalt "Liebe Bank, überweisen Sie bitte 10€ an Lisa" sowie dazu eine Signatur von mir. Die Bank kennt meinen öffentlichen Schlüssel und prüft jetzt nur die Signatur und sagt die Signatur ist korrekt.
Nun bekommt die Bank noch eine E-Mail mit dem Inhalt "Liebe Bank, überweisen Sie bitte 1000 € an Lisa" sowie dazu die Signatur von der vorherigen E-Mail. Wenn jetzt wieder nur die Signatur geprüft wird, dann stimmt die Signatur, aber passt nicht zum Text.

Deshalb soll man einen gegebenen Plaintext mit einer gegebenen Signatur (+key) prüfen können.

**Comment by lisaTeis** [comment]
Okay, klingt sinnvoll. Das habe ich nicht bedacht. Kann ich noch rein machen.

**Comment by lisaTeis** [comment]
@kmindi Ist die Implementierung so gedacht?
@Override
	public boolean validateSignature (AbstractSCCSignature signature, AbstractSCCKey key) throws SCCException
	{
		SCCSignature sigForPlain = this.sign(key);
		return signature.toBytes().equals(sigForPlain.toBytes());
	}

Hab es jetzt mal so aufgenommen. Ansonsten passe ich es an. Will nur sicher gehen, ob ich es richtig verstanden habe

**Comment by kmindi** [comment]
Ja, das sieht gut aus. Kannst du dafür einen Testfall hinzufügen? Also so wie ich es oben beschrieben habe, mit zwei verschiedenen texten, dass dann einmal erwartet wird dass eine andere signatur rauskommt (assertNotEquals)

**Comment by lisaTeis** [comment]
Mach ich gleich noch rein.

**Comment by lisaTeis** [comment]
@kmindi Wie besprochen hab ich den Test für validate Signature (testValidateSignature()) in die Klasse testPlaintextContainer eingefügt. Leider kommt immer das falsche Ergebnis raus. Kannst du mal schauen ob du herausfindest an was es liegen könnte? Es scheint als hätte der gleiche Plaintext nicht immer die gleiche Signatur und ich weiß nicht warum.
